// composables/ObjectManagers/kitchen/kitchenSearch.js
// File: composables/EntityManagers/kitchen/kitchenSearch.js

export const useKitchenSearch = (location, additionalKeywords = []) => {
  // Define a comprehensive list of keywords for various types of kitchens.
  const keywords = [
    "Kitchen",
    "Restaurant",
    "Restaurant Kitchen",
    "Commercial Kitchen",
    "High Street Kitchen",
    "Ghost Kitchen",
    "Private Kitchen",
    "Home Kitchen",
    "Prison Kitchen",
    "Cruise Ship Kitchen",
    "Canteen",
    "Catering Kitchen",
    "Pop-up Kitchen",
    "Food Preparation",
    "Institutional Kitchen",
    "Hotel Kitchen",
    "Gourmet Kitchen",
    "Modern Kitchen",
    "Industrial Kitchen",
    "Corporate Kitchen",
    "Mobile Kitchen",
    "Truck Kitchen",
    "Food Truck Kitchen",
    "Outdoor Kitchen",
    "Rooftop Kitchen",
    "Experimental Kitchen",
    "Test Kitchen",
    "Bakery Kitchen",
    "Coffee Shop Kitchen",
    "Café Kitchen",
    "Bistro Kitchen",
    "Bar Kitchen",
    "Pub Kitchen",
    "Fast Food Kitchen",
    "Drive-thru Kitchen",
    "Express Kitchen",
    "Buffet Kitchen",
    "Family Kitchen",
    "Institutional Food Service",
    "School Kitchen",
    "University Kitchen",
    "Hospital Kitchen",
    "Healthcare Kitchen",
    "Retirement Home Kitchen",
    "Resort Kitchen",
    "Event Kitchen",
    "Banquet Kitchen",
    "Conference Kitchen",
    "Steakhouse Kitchen",
    "Pizzeria Kitchen",
    "Sushi Kitchen",
    "Asian Kitchen",
    "Italian Kitchen",
    "French Kitchen",
    "Mediterranean Kitchen",
    "Fusion Kitchen",
    "Local Kitchen",
    "Farm-to-Table Kitchen",
    "Organic Kitchen",
    "Sustainable Kitchen",
  ].concat(additionalKeywords);

  // Pass the collection name "kitchens", the keywords, and the location into the merged search composable.
  return useFirestoreGoogleMergeSearch("kitchens", keywords, location);
};
